// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghbfmlubifwlrpwpuzye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoYmZtbHViaWZ3bHJwd3B1enllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NjQ2NjYsImV4cCI6MjA2NTQ0MDY2Nn0._7_58L6EEvZN-gJxXY_SI6lSpFF2KbAtabERvFDqmak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);